version: '3.5'
services:
  eureka:
    build: eureka-naming-server
    hostname: eureka
    networks:
      dev_network:
        aliases:
          - eureka
    ports:
      - "8762:8762"

  calculate-sever:
    build: calculate-server
    hostname: calculate-sv
    restart: always
    networks:
      dev_network:
        aliases:
         - calculate-sv
    ports:
      - "9090-9099:9090"

  application:
    build: application
    hostname: application
    restart: always
    networks:
      dev_network:
        aliases:
          - application
    ports:
      - "8181:8181"


networks:
  dev_network:


